// flow-typed signature: 71823544f06e132fe1346d61a6191a31
// flow-typed version: <<STUB>>/harmony-reflect_v1.6.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'harmony-reflect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'harmony-reflect' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'harmony-reflect/reflect' {
    declare module.exports: any;
}

// Filename aliases
declare module 'harmony-reflect/reflect.js' {
    declare module.exports: $Exports<'harmony-reflect/reflect'>;
}
