// flow-typed signature: e6358bb8e4abe7199b4923bbc932e8e8
// flow-typed version: <<STUB>>/react-iframe_v1.3.3/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-iframe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-iframe' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-iframe/demo/index' {
    declare module.exports: any;
}

declare module 'react-iframe/demo/react-iframe.min' {
    declare module.exports: any;
}

declare module 'react-iframe/demo/webpack.config' {
    declare module.exports: any;
}

declare module 'react-iframe/gulpfile' {
    declare module.exports: any;
}

declare module 'react-iframe/index.min' {
    declare module.exports: any;
}

// Filename aliases
declare module 'react-iframe/demo/index.js' {
    declare module.exports: $Exports<'react-iframe/demo/index'>;
}
declare module 'react-iframe/demo/react-iframe.min.js' {
    declare module.exports: $Exports<'react-iframe/demo/react-iframe.min'>;
}
declare module 'react-iframe/demo/webpack.config.js' {
    declare module.exports: $Exports<'react-iframe/demo/webpack.config'>;
}
declare module 'react-iframe/gulpfile.js' {
    declare module.exports: $Exports<'react-iframe/gulpfile'>;
}
declare module 'react-iframe/index.min.js' {
    declare module.exports: $Exports<'react-iframe/index.min'>;
}
