// flow-typed signature: 286b8ced3b52b468d99315388c668977
// flow-typed version: <<STUB>>/react-frame_v2.1.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-frame'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-frame' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-frame/dist/frame' {
    declare module.exports: any;
}

declare module 'react-frame/example/app' {
    declare module.exports: any;
}

declare module 'react-frame/example/json-css' {
    declare module.exports: any;
}

declare module 'react-frame/lib/frame' {
    declare module.exports: any;
}

declare module 'react-frame/webpack.config' {
    declare module.exports: any;
}

// Filename aliases
declare module 'react-frame/dist/frame.js' {
    declare module.exports: $Exports<'react-frame/dist/frame'>;
}
declare module 'react-frame/example/app.js' {
    declare module.exports: $Exports<'react-frame/example/app'>;
}
declare module 'react-frame/example/json-css.js' {
    declare module.exports: $Exports<'react-frame/example/json-css'>;
}
declare module 'react-frame/index' {
    declare module.exports: $Exports<'react-frame'>;
}
declare module 'react-frame/index.js' {
    declare module.exports: $Exports<'react-frame'>;
}
declare module 'react-frame/lib/frame.js' {
    declare module.exports: $Exports<'react-frame/lib/frame'>;
}
declare module 'react-frame/webpack.config.js' {
    declare module.exports: $Exports<'react-frame/webpack.config'>;
}
