// flow-typed signature: a56a04cca7a52f08e5a7c591007e51cc
// flow-typed version: <<STUB>>/styled-css-grid_v1.2.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-css-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-css-grid' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-css-grid/dist/styled-css-grid.esm' {
    declare module.exports: any;
}

declare module 'styled-css-grid/dist/styled-css-grid.umd' {
    declare module.exports: any;
}

// Filename aliases
declare module 'styled-css-grid/dist/styled-css-grid.esm.js' {
    declare module.exports: $Exports<'styled-css-grid/dist/styled-css-grid.esm'>;
}
declare module 'styled-css-grid/dist/styled-css-grid.umd.js' {
    declare module.exports: $Exports<'styled-css-grid/dist/styled-css-grid.umd'>;
}
